import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import WizardFormProvider from "./context/WizardFormContext";

const fontSans = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fontSans.variable} h-full antialiased dark`}>
      <body className="min-h-full flex flex-col">
        <WizardFormProvider>{children}</WizardFormProvider>
      </body>
    </html>
  );
}
